1. Matrix Addition: Write a Python program to add two matrices represented as nested lists.

In [10]:
def add_matrices(matrix1,matrix2):
    if len(matrix1)!=len(matrix2):
        return None
    matrix=[[0,0,0],
            [0,0,0],
            [0,0,0]]
    for i in range(len(matrix1)):
        for j in range(len(matrix2)):
            matrix[i][j]=matrix1[i][j]+matrix2[i][j]
    return matrix
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]
matrix = add_matrices(matrix1, matrix2)
print("Matrix as Nested list:", matrix)

if matrix:
    print("Resultant Matrix after addition:")
    for row in matrix:
        print(row)
else:
    print("Matrices cannot be added. Dimensions are different.")
l=[]

Matrix as Nested list: [[10, 10, 10], [10, 10, 10], [10, 10, 10]]
Resultant Matrix after addition:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


2. Flatten Nested List: Write a Python program to flatten a given nested list and convert it into a single-dimensional list.

In [11]:
List =[[11, 22, 33, 44], [55, 66, 77], [88, 99, 100]]
lis=[]
for i in List:
    lis.extend(i)
print(lis)    

[11, 22, 33, 44, 55, 66, 77, 88, 99, 100]


3. List Element Frequency: Given a nested list containing lists of integers, write a Python program to count the frequency of each element in the entire nested list.

In [12]:
list = [[9, 8, 7,3],[6, 5, 4],[3, 2, 1]]
lis=[]

for i in list:
    count=0
    for j in i:
        count=count+1
    lis.append(count)    
print(lis)        

[4, 3, 3]


4. Transpose Matrix: Write a Python program to transpose a given matrix represented as a nested list.

In [13]:
import numpy as np
matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix)
print("\n")
print(np.transpose(matrix))


[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [14]:
import numpy
matrix=[[2,3,4],[2,3,2],[2,1,4]]
print(numpy.transpose(matrix))

[[2 2 2]
 [3 3 1]
 [4 2 4]]


5. List of Lists Concatenation: Given a list of nested lists, write a Python program to concatenate all the sublists into a single flat list.

In [15]:
list1=[2,1,3,4,2]
list2=[1,2,3,4]
list=list1+list2
print(list)

[2, 1, 3, 4, 2, 1, 2, 3, 4]


In [16]:

list = [[1, 2, 3], [4, 5], [6, 7, 8]]

list1 = [x for x in list for x in x ]

print("Flat list:",list1)


Flat list: [1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
list = [[1, 2, 3], [4, 5], [6, 7, 8]]
lis=[]

for i in list:
    lis.extend(i)
print(lis)    

[1, 2, 3, 4, 5, 6, 7, 8]


6. Tuple Concatenation: Write a Python program to concatenate two tuples and create a new tuple.

In [18]:
tuple1=(1,2,3,4)
tuple2=(2,3,1,2)
tuple=tuple1+tuple2
print(tuple)

(1, 2, 3, 4, 2, 3, 1, 2)


7. Tuple Unpacking: Given a tuple with three elements (x, y, z), write a Python program to unpack the tuple and assign the values to three variables.

In [19]:
tuple=(10,20,30)
x,y,z=tuple
print("x:",x)
print("y:",y)
print("z:",z)


x: 10
y: 20
z: 30


8. Tuple Sorting: Write a Python program to sort a tuple of integers in ascending order.

In [1]:
tuple1=(10,2,1,5,11,20,30)
x=sorted(tuple1)
print(tuple(x))

(1, 2, 5, 10, 11, 20, 30)


9. Tuple Frequency Count: Given a tuple containing various elements, write a Python program to count the frequency of a specific element in the tuple.

In [2]:
tuple1=(10,2,1,2,1,1,3,5,11,20,30)
x=1
count=0
for i in tuple1:
    if i==x:
        count=count+1
print("element",x,"is",count,"times.")        

element 1 is 3 times.


10. Tuple to List: Write a Python program to convert a tuple into a list.

In [3]:
tuple1=(10,2,1,2,1,1,3,5,11,20,30)
print("list is:",list(tuple1))

list is: [10, 2, 1, 2, 1, 1, 3, 5, 11, 20, 30]


11. Tuple Reversal: Write a Python program to reverse a tuple without using any built-in functions.

In [4]:
tuple1=(10,2,1,2,1,1,3,5,11,20,30)
tupl=tuple1[::-1]
print(tupl)

(30, 20, 11, 5, 3, 1, 1, 2, 1, 2, 10)


12. Tuple Slicing: Given a tuple, write a Python program to extract a slice of elements from it.

In [5]:
tuple1=(10,2,1,2,1,1,3,5,11,20,30)
print(tuple1[:3])
print(tuple1[1:8])
print(tuple1[-11:])
print(tuple1[-5:-2])
print(tuple1[::-1])

(10, 2, 1)
(2, 1, 2, 1, 1, 3, 5)
(10, 2, 1, 2, 1, 1, 3, 5, 11, 20, 30)
(3, 5, 11)
(30, 20, 11, 5, 3, 1, 1, 2, 1, 2, 10)


13. Duplicate Removal: Write a Python program that takes a list of elements as input and creates a new set containing only the unique elements from the list.

In [6]:
set={10,2,1,2,1,1,3,5,11,20,30}
print(set)


{1, 2, 3, 5, 10, 11, 20, 30}


In [1]:
list=[1,2,3,4,2,1,2,3,4,1,2,2,3,4,5,5]
Set=set()
for i in list:
    Set.add(i)
print("New set:",Set)    
    

New set: {1, 2, 3, 4, 5}


14. Set Intersection: Given two sets A and B, write a Python program to find their intersection and print the common elements.

In [2]:
Newset={1, 2, 3, 4, 5}
Set={10,2,1,2,1,1,3,5,11,20,30}
set=Set.intersection(Newset) 
print(set)

{1, 2, 3, 5}


In [3]:
set_A = {1, 2, 3, 4, 5}
set_B = {4, 5, 6, 7, 8}
c=set_A & set_B
print(c)

{4, 5}


15. Dictionary Manipulation: Given a dictionary with student names as keys and their corresponding scores as values, write a Python program to add a new student to the dictionary and update the score of an existing student.

In [4]:
StudentNames={'T':80,'TT':81,'A':82}
name=input("name:")
Newmarks=int(input("marks:"))
StudentNames[name]=Newmarks
print(name,":",Newmarks)
print(StudentNames)    

name:tt
marks:800
tt : 800
{'T': 80, 'TT': 81, 'A': 82, 'tt': 800}


16. Dictionary Keys and Values: Write a Python program that takes a dictionary as input and prints all the keys and values in separate lines.

In [5]:
dic={}

n=int(input("Enter number:"))
for i in range(n):
    key=input("Enter keyes")
    value=int(input("Enter value"))
    dic[key]=value

print("dictonary",dic)
print(dic.keys())
print(dic.values())

Enter number:2
Enter keyestt
Enter value40
Enter keyesttt
Enter value222
dictonary {'tt': 40, 'ttt': 222}
dict_keys(['tt', 'ttt'])
dict_values([40, 222])


17. Dictionary Length: Write a Python program to calculate and print the number of key-value pairs in a given dictionary.

In [6]:
StudentNames={'T':80,'TT':81,'A':82}
print("Number of pairs is:",len(StudentNames))

Number of pairs is: 3


18. Dictionary Value Search: Given a dictionary of items and their prices, write a Python program to search for an item based on its price and print the item’s name.

In [7]:
fruit = {'apple' : 1, 'mango' : 2, 'cherry' : 3}
print("The original dictionary is : " + str(fruit))
val = 3
for key in fruit:
    if fruit[key] == val:
        res = key
print("The key corresponding to value : " + str(res))

The original dictionary is : {'apple': 1, 'mango': 2, 'cherry': 3}
The key corresponding to value : cherry


In [5]:
StudentNames={'T':80,'TT':81,'A':82}
print(StudentNames.values())

dict_values([80, 81, 82])


19. Dictionary Merging: Given two dictionaries, write a Python program to merge them into a single dictionary and print the result.

In [6]:
d1={'T':80,'TT':81,'A':82}
d2={'T2':30,'2TT':831,'2A':832}
d1.update(d2)
print(d1)

{'T': 80, 'TT': 81, 'A': 82, 'T2': 30, '2TT': 831, '2A': 832}


In [7]:
def merge(d):
    d1={'T':80,'TT':81,'A':82}
    d2={'T2':30,'2TT':831,'2A':832}
    d1.update(d2)
    return d1
merge(d1)

{'T': 80, 'TT': 81, 'A': 82, 'T2': 30, '2TT': 831, '2A': 832}

20. Dictionary Key Removal: Given a dictionary of items and their quantities, write a Python program to remove a specific item from the dictionary based on user input.

In [13]:
items = {'apple': 5, 'banana': 3, 'orange': 7, 'grape': 2}

s=input("Which want to remove?")
if s in items:
    del items[s]
    print(f"{s} has been removed")
else:
    print(s,'dose not exist')
print("Updated dictonary:",items)    

Which want to remove?apple
apple has been removed
Updated dictonary: {'banana': 3, 'orange': 7, 'grape': 2}


21. Dictionary Sorting: Given a dictionary with names as keys and corresponding ages as values, write a Python program to sort the dictionary based on age in ascending order.

In [41]:

ages = {'Tamanna':22,'Tanshin':23,'Tasbi':8}


sorted_ages= dict(sorted(ages.items(), key=lambda item: item[1]))

print(sorted_ages )


{'Tasbi': 8, 'Tamanna': 22, 'Tanshin': 23}


22. Dictionary Frequency Count: Write a Python program that takes a string as input and creates a dictionary containing each character as a key and its frequency as the value.

In [2]:
dict={}
n=int(input())
for i in range(n):
    keys=input()
    values=len(keys)
    dict[keys]=values
print(dict)  

2
tanannana
tannn
{'tanannana': 9, 'tannn': 5}


23. Dictionary Comprehension: Given a list of integers, write a Python program to create a dictionary where the keys are the elements from the list, and the values are their squares

In [8]:
# Python code to demonstrate dictionary 
# creation using list comprehension
myDict = {x: x**2 for x in [1,2,3,4,5]}
print (myDict)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [4]:
list=[1,2,3,4,5]
dic={x: x**2 for x in list}
print(dic)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


24. Dictionary Key Check: Write a Python program that takes a key as input and checks if it exists in a given dictionary. Print “Key Found” if the key is present and “Key Not Found” otherwise.

In [6]:
dic={'Tasbi': 8, 'Tamanna': 22, 'Tanshin': 23}
key=input()
if key in dic:
    print("key found")
else:
    print("not found")

Tasbi
key found


25. Access Nested Dictionary: Given a nested dictionary containing student details, write a Python program to access and print specific information such as a student’s name, age, and address.

In [9]:

student_details = {
    'student1': {
        'name': 'Tamanna',
        'age': 20,
        'address': 'Dhaaka'
    },
    'student2': {
        'name': 'Tanshin',
        'age': 22,
        'address': 'Manikgang'
    }
}


name=student_details['student1']['name']
age=student_details['student1']['age']
adress=student_details['student1']['address']
print("Student 1 details:")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Address: {adress}")


Student 1 details:
Name: Tamanna
Age: 20
Address: Dhaaka


26. Nested Dictionary Length: Write a Python program to calculate and print the total number of key-value pairs in a nested dictionary.

In [2]:

student_details = {
    'student1': {
        'name': 'Tamanna',
        'age': 20,
        'address': 'Dhaaka'
    },
    'student2': {
        'name': 'Tanshin',
        'age': 22,
        'address': 'Manikgang'
    }
}
nested_dict = {'a': 1, 'b': {'c': 2, 'd': {'e': 3, 'f': 4}}, 'g': 5}
print(len(student_details))
print(len(nested_dict))

2
3


In [1]:
# Function to calculate the total number of key-value pairs in a nested dictionary
def nested_dict_length(nested_dict):
    total_length = 0
    for value in nested_dict.values():
        if isinstance(value, dict):
            total_length += nested_dict_length(value)  # Recursively count key-value pairs in nested dictionary
        else:
            total_length += 1  # Count each key-value pair
    return total_length

# Example nested dictionary
nested_dict = {'a': 1, 'b': {'c': 2, 'd': {'e': 3, 'f': 4}}, 'g': 5}

# Calculate the total number of key-value pairs
total_pairs = nested_dict_length(nested_dict)

# Print the result
print("Total number of key-value pairs in the nested dictionary:", total_pairs)


Total number of key-value pairs in the nested dictionary: 5


27. Nested Dictionary Update: Given a nested dictionary of employee details, write a Python program to update an employee’s salary based on their employee ID.

In [6]:
employee_details = {
    101: {'name': 'Alice', 'salary': 50000},
    102: {'name': 'Bob', 'salary': 60000},
    103: {'name': 'Charlie', 'salary': 55000}
}
employee_id = 102
new_salary = 65000
if employee_id in employee_details:
    employee_details[employee_id]['salary'] = new_salary
    print(f"Salary updated for employee with ID {employee_id}.")
else:
    print(f"No employee found with ID {employee_id}.")
print(employee_details)
print("\n")
for emp_id, details in employee_details.items():
    print(f"Employee ID: {emp_id}, Name: {details['name']}, Salary: {details['salary']}")



Salary updated for employee with ID 102.
{101: {'name': 'Alice', 'salary': 50000}, 102: {'name': 'Bob', 'salary': 65000}, 103: {'name': 'Charlie', 'salary': 55000}}


Employee ID: 101, Name: Alice, Salary: 50000
Employee ID: 102, Name: Bob, Salary: 65000
Employee ID: 103, Name: Charlie, Salary: 55000


28. Nested Dictionary Sorting: Given a nested dictionary containing product details (product name, price, and quantity), write a Python program to sort the products based on their prices in ascending order

In [9]:

product_details = {
    'product1': {'name': 'Laptop', 'price': 1000, 'quantity': 5},
    'product2': {'name': 'Phone', 'price': 500, 'quantity': 10},
    'product3': {'name': 'Tablet', 'price': 700, 'quantity': 3}
}


sorted_products = dict(sorted(product_details.items(), key=lambda item: item[1]['price']))


print("Products sorted based on prices in ascending order:")
for product, details in sorted_products.items():
    print(f"Product: {product}, Name: {details['name']}, Price: {details['price']}, Quantity: {details['quantity']}")


Products sorted based on prices in ascending order:
Product: product2, Name: Phone, Price: 500, Quantity: 10
Product: product3, Name: Tablet, Price: 700, Quantity: 3
Product: product1, Name: Laptop, Price: 1000, Quantity: 5
